## Load data

### Subtask:
Load the dataset from the provided path `/content/titanic.xlsx` into a pandas DataFrame.

**Reasoning**:
Import pandas and load the data from the specified Excel file into a DataFrame.

In [1]:
import pandas as pd

df = pd.read_excel('/content/titanic.xlsx')

**Reasoning**:
The data has been loaded, the next step is to display the first few rows of the DataFrame to confirm the loading was successful.

In [2]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Basic eda

### Subtask:
Perform basic exploratory data analysis using `head()`, `tail()`, `describe()`, and `shape`.

**Reasoning**:
Display the first 5 rows, last 5 rows, descriptive statistics, and the shape of the dataframe to perform basic EDA.

In [3]:
display(df.head())
display(df.tail())
display(df.describe())
display(df.shape)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

(891, 12)

## Identify and handle missing values

### Subtask:
Identify missing values in the dataset and apply appropriate techniques to handle them.

**Reasoning**:
Calculate and display the number of missing values per column to identify columns with missing data.

In [4]:
missing_values = df.isnull().sum()
print("Missing values per column:")
print(missing_values)

Missing values per column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

**Reasoning**:
Handle missing values in the 'Age', 'Cabin', and 'Embarked' columns based on the extent of missingness and the nature of the data. For 'Age', impute with the median. For 'Cabin', which has a high percentage of missing values, drop the column. For 'Embarked', impute with the mode as it is a categorical variable with few missing values.

In [5]:
df['Age'].fillna(df['Age'].median(), inplace=True)
df.drop('Cabin', axis=1, inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

/tmp/ipython-input-5-329121024.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)
/tmp/ipython-input-5-329121024.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

**Reasoning**:
Verify that all missing values have been handled by calculating and displaying the number of missing values for each column again.

In [6]:
missing_values_after = df.isnull().sum()
print("Missing values per column after handling:")
print(missing_values_after)

Missing values per column after handling:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

## Check and handle duplicates

### Subtask:
Check for duplicate rows and remove them if any are found.

**Reasoning**:
Check and remove duplicate rows in the DataFrame.

In [7]:
initial_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows before removal: {initial_duplicates}")

if initial_duplicates > 0:
    df.drop_duplicates(inplace=True)
    print("Duplicate rows removed.")

duplicates_after_removal = df.duplicated().sum()
print(f"Number of duplicate rows after removal: {duplicates_after_removal}")

Number of duplicate rows before removal: 0
Number of duplicate rows after removal: 0

## Identify and handle outliers

### Subtask:
Identify outliers in numerical columns and handle them using appropriate methods.

**Reasoning**:
Select numerical columns, calculate IQR, define outlier bounds, identify outliers, and handle them by capping within a single code block.

In [8]:
import numpy as np

numerical_cols = df.select_dtypes(include=np.number).columns

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    if not outliers.empty:
        df[col] = np.where(df[col] < lower_bound, lower_bound, df[col])
        df[col] = np.where(df[col] > upper_bound, upper_bound, df[col])
        print(f"Outliers in column '{col}' handled by capping.")
    else:
        print(f"No outliers found in column '{col}'.")

No outliers found in column 'PassengerId'.
No outliers found in column 'Survived'.
No outliers found in column 'Pclass'.
Outliers in column 'Age' handled by capping.
Outliers in column 'SibSp' handled by capping.
Outliers in column 'Parch' handled by capping.
Outliers in column 'Fare' handled by capping.

## Apply data encoding

### Subtask:
Apply suitable data encoding techniques to categorical attributes.

**Reasoning**:
Identify categorical columns and apply one-hot encoding to the 'Sex' and 'Embarked' columns since they are nominal. Display the head of the dataframe to verify the encoding.

In [9]:
categorical_cols = df.select_dtypes(include='object').columns
print("Categorical columns:")
print(categorical_cols)

df = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

display(df.head())

Categorical columns:
Index(['Name', 'Sex', 'Ticket', 'Embarked'], dtype='object')

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Sex_male,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1.0,0.0,A/5 21171,7.2500,True,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1.0,0.0,PC 17599,65.6344,False,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0.0,0.0,STON/O2. 3101282,7.9250,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1.0,0.0,113803,53.1000,False,False,True
4,5,0,3,"Allen, Mr. William Henry",35.0,0.0,0.0,373450,8.0500,True,False,True